### ISSUE TITLE
ICS consumer chain generation

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#112]
# TODO
- [x] Add / remove ICS as expected with tags
- [x] Add new 'staking' option. This feature is on by default but hidden
    - If ICS is used, then staking is disabled, removes all references for staking. \
    - Also remove Distr, Mint, etc.
- [x]  Integrate Interchaintest w/ simple ICS test ( https://github.com/strangelove-ventures/interchaintest/pull/1088 )
- [x] Add test_ics_node.sh instead of test_node.sh w/ Stide's provider hack
- [x] CI: Run test_ics_node.sh for ics chain (matrix?)
- [x] Speed up CI
- [ ] Unit Test (ref: stride, neutron)
- [x] see if we can abstract in setup.go so we can reuse standard test instead of new ones
    - [ ] do for all e2e test
- [x] Update to ICTest v8.3.0 + IBC  validation (from upstream ICT)
- [ ] Local Interchain proper generation (remove default)
- [ ] In UI, if ICS selected, deselect POA

# Test Basic
```
make install && rm -rf testics1/
spawn new testics1 --disable=poa,tf,globalfee,packetforward,ibc-ratelimit,cw,wasm-lc,ignite-cli

spawn new chain1 --disable=ics
spawn new chain2
```

**Comment by reecepbcups** [comment]
- [ ] merge different ChainSepc array setups into 1. This way it can be used in all the test. Then just have the provider setup automatically. We just switch between Ethos, CosmosHub, and Saga (only allow 1 for an ICS chain, Hub default)
- [ ] Local-Interchain have ICS be renamed to the normal file start testnet (For JSON generation, maybe have a struct instead of the raw JSON files. (we only bech32 convert wasm1 & wasmd info, so other networks like cosmoshub, neutron, ethos, are safe to support directly in the file)
- [ ] Local-IC delete encoding-options which are not used (probably part of the above JSON builder)


TODO: push up ICS 4.1.0 with heighliner to confirm `make template-ics` and `make template-staking`'s `make ictest-basic` function as expected
