### ISSUE TITLE
validate spawn new chain works

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#17]
## Part 1
- [ ] go mod download & cache
- [ ] ensure go unit test passes
- [ ] ensure build passes & start chain from test_node script
- [ ] Ensure no references to disabled modues within the new user facing chains

## Part 2
- [ ] build chains of different types (i.e. change bin, prefix). randomization of modules. Grep no instances in each
