### ISSUE TITLE
EPIC: Docs v1

### ISSUE THREAD

**Issue by jonathanpberger** [rollchains/spawn#175]
- [x] https://github.com/rollchains/spawn/pull/84
- [x] https://github.com/rollchains/spawn/pull/69
- [x] https://github.com/rollchains/spawn/pull/91
- [x] https://github.com/rollchains/spawn/pull/34
- [x] https://github.com/rollchains/spawn/pull/93
