### ISSUE TITLE
EPIC: ICS

### ISSUE THREAD

**Issue by jonathanpberger** [rollchains/spawn#178]
- [x] https://github.com/rollchains/spawn/pull/129
- [x] https://github.com/rollchains/spawn/issues/127
- [x] https://github.com/rollchains/spawn/issues/112
- [ ] https://github.com/rollchains/spawn/pull/158
- [x] https://github.com/rollchains/spawn/pull/159
- [x] https://github.com/rollchains/spawn/pull/133
- [x] https://github.com/rollchains/spawn/pull/135
- [x] https://github.com/rollchains/spawn/pull/143
- [ ] https://github.com/rollchains/spawn/pull/148
- [ ] https://github.com/rollchains/spawn/pull/149
- [x] https://github.com/rollchains/spawn/pull/150
- [x] https://github.com/rollchains/spawn/pull/164

**Comment by reecepbcups** [comment]
completed ICS integration, coordinating with Informal, testing, and the first ICS consumer testnet build with spawn was launched via Hypha. All is good.
