### ISSUE TITLE
EPIC: UX

### ISSUE THREAD

**Issue by jonathanpberger** [rollchains/spawn#179]
- [ ] https://github.com/rollchains/spawn/pull/8
- [ ] https://github.com/rollchains/spawn/pull/18
- [ ] https://github.com/rollchains/spawn/pull/72
- [ ] https://github.com/rollchains/spawn/pull/39
- [ ] https://github.com/rollchains/spawn/pull/36
- [ ] https://github.com/rollchains/spawn/pull/145
- [ ] https://github.com/rollchains/spawn/pull/56
- [ ] https://github.com/rollchains/spawn/pull/65
- [ ] https://github.com/rollchains/spawn/pull/40
- [ ] https://github.com/rollchains/spawn/pull/77
- [ ] https://github.com/rollchains/spawn/pull/100
- [ ] https://github.com/rollchains/spawn/pull/63
- [ ] https://github.com/rollchains/spawn/pull/89
- [x] https://github.com/rollchains/spawn/issues/97
