### ISSUE TITLE
EPIC: Spawn should have a Prod env

### ISSUE THREAD

**Issue by jonathanpberger** [rollchains/spawn#180]
- [x] https://github.com/rollchains/spawn/pull/105
- [x] https://github.com/rollchains/spawn/pull/107
- [x] https://github.com/rollchains/spawn/pull/109

**Comment by reecepbcups** [comment]
completed as of v0.50.7 :partying_face:
