### ISSUE TITLE
EPIC: UX v2

### ISSUE THREAD

**Issue by jonathanpberger** [rollchains/spawn#182]
- [x] https://github.com/rollchains/spawn/issues/134
- [x] https://github.com/rollchains/spawn/issues/166
- [x] https://github.com/rollchains/spawn/issues/160
- [x] https://github.com/rollchains/spawn/pull/176
- [x] https://github.com/rollchains/spawn/issues/155
- [x] https://github.com/rollchains/spawn/issues/167
- [x] https://github.com/rollchains/spawn/issues/174
- [x] https://github.com/rollchains/spawn/issues/202
- [x] https://github.com/rollchains/spawn/pull/214

**Comment by reecepbcups** [comment]
All handled that we plan to do
