### ISSUE TITLE
EPIC: UI

### ISSUE THREAD

**Issue by jonathanpberger** [rollchains/spawn#184]
- [x] Block explorer (ping.pub) https://github.com/rollchains/spawn/pull/187
- [x]  Cosmology (see https://strangeloveventures.slack.com/archives/C04F3B0V8CS/p1718373933256779)
- [ ] [ChainChainUI](https://github.com/rollchains/spawn-ui)

**Comment by reecepbcups** [comment]
Cosmology work has been integrated on their end & fully functions as expected with latest v0.50.7.

ChainChainUI work begins monday

**Comment by reecepbcups** [comment]
last UI option here (ChainChainUI w/ Galen) is out of scope of spawn directly and more so a new product (since it is for launching a new network, not using spawn directly)

Closing as other 2 have been completed
