### ISSUE TITLE
EPIC: Modules to Add

### ISSUE THREAD

**Issue by Reecepbcups** [rollchains/spawn#41]
# Modules
- [x] packetforward https://github.com/rollchains/spawn/pull/47
- [x] PoA
- [x] TokenFactory
- [x] GlobalFee (0 fees for testnets, test with ictest)

# Opt-In
- [x] https://github.com/rollchains/spawn/pull/103
- [x] https://github.com/rollchains/spawn/pull/119
- [x] 08 Wasm Light Client https://github.com/rollchains/spawn/pull/85
- [ ] [block-sdk](https://github.com/skip-mev/block-sdk)
- [ ]  [Larry’s accountabstraction (on xion)
](https://github.com/larry0x/abstract-account)- [ ] [OJO Oracle](https://x.com/rollchains/status/1778437885848436861)
- [x] https://github.com/ojo-network/ojo
- [x] https://github.com/Stride-Labs/ibc-rate-limiting ([v50 branch](https://github.com/Stride-Labs/ibc-rate-limiting/commits/feat/sdk-v50))
    - [x] E2E test
- [x] Ignite-CLI
- [ ] Cosmos-EVM
- [ ] TiaBlob
- [ ] eIBC

## previous ideas

- Osmosis GAMM (apache-2, upgrade from dymensionxyz ?)
- [Polaris](https://github.com/berachain/polaris/tree/main/cosmos) w/ a separate EVM simapp most likely
- [Ethermint v50](https://github.com/crypto-org-chain/ethermint) from cro (off)]
- Omni, needs bank<>erc20 wrapper

**Comment by suyog-bhat** [comment]
How can we add staking and nft module.?

**Comment by reecepbcups** [comment]
@suyog-bhat These are already provided by default (to use staking, when you `spawn new mychain`, de-select the proof-of-authority option

NFT comes standard with all no matter what

**Comment by reecepbcups** [comment]
Closing for now as we know which modules we want in the near future.
