### ISSUE TITLE
open sourcing todos

### ISSUE THREAD

**Issue by Reecepbcups** [rollchains/spawn#73]
we need to do the following to open source the repo & release spawn

## Part 1
- Move modules -> Strangelove org & namespace from personal. Tag latest as v0.50
  - [x] https://github.com/rollchains/spawn/pull/81
  - [x] https://github.com/rollchains/spawn/pull/82
- [x] Verify rollchains namespace is used everywhere (https://github.com/rollchains/spawn/pull/78)
- [x] Release GlobalFee, Tokenfactory, and PoA v0.50 + latest PFM
- [x] Tag v8.2 interchaintest w/ [PR 1006](https://github.com/strangelove-ventures/interchaintest/pull/1006) for interaction. Ensure that’s used in make file download
- [x] Re-review, cleanup todos
- [x] Push new generated chains to CI passing - https://github.com/rollchains/spawn/pull/87
- [x] Move to main

# Part 2
- [x] Replace readme main video -> the new one from jack
- [x] better disabled UX - https://github.com/rollchains/spawn/pull/89
- [x] Make main branch **0.50.x** (no v) or `release/v0.50` ? & set as the default branch
- [x] Update readme to use local-ic interact instead of curl
- [x] Push new generated chains to CI passing (again) + `make testnet`
  - [x] minimal
  - [x] base
  - [x] mywaslc
  - [x] mycw
- [x] Tag spawn v0.50.0
- [x] Point website to spawn 
- [x] Open Source
- [x] Add to https://github.com/cosmos/awesome-cosmos "Templates" section

**Comment by reecepbcups** [comment]
woo!
